# Generated by Django 4.2.10 on 2026-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_testaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='topics/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': "O'quv qo'llanma", 'verbose_name_plural': "O'quv qo'llanmalar"},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Test savoli', 'verbose_name_plural': 'Test savollari'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video dars', 'verbose_name_plural': 'Video darslar'},
        ),
    ]
